### ISSUE TITLE
Deploying latest artifact for other branches

### ISSUE THREAD

**Issue by nrambeck** [sparkbox/mina-circle#40]
In the last week we have experienced Mina Circle deploying artifacts for branches other than the one specific. In both cases, we specified a branch to deploy, but the latest artifact for that branch was not actually deployed. Instead of some other artifact was. We have found that rebuilding the branch in CircleCI will resolve this issue. Because of this, it appears that Mina Circle is deploying the latest artifact of any branch from CircleCI, rather than the latest from the branch specified.

**Comment by nrambeck** [comment]
During a debug session we noticed that the API call used when deploying a branch, did not properly set the branch GET query parameter. Here is what was used.

`https://circleci.com/api/v1.1/project/github/XXXXXX/XXXXXX/latest/artifacts?filter=successful&branch`

**Comment by patricksimpson** [comment]
Closing this issue as it seems to be resolved in the latest version of mina-circle (1.3.5).
